### ISSUE TITLE
cost of clojurebridge.org email addresses

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/board#10]
The [checklist][1] currently includes this note under __Google Apps account__:

> $5/person each month will be added up to a current charge.

Is this still accurate, @yokolet? If so I suggest we keep <info@clojurebridge.org> but relinquish our personal clojurebridge.org email addresses. Spending $300 per year on email addresses isn't warranted. I hope to learn that this note is no longer applicable, in which case you should disregard my previous comments. :)

[1]: https://github.com/ClojureBridge/board/blob/02031ba8be91d1e7d1f1cf4b98e9201b2ea29260/checklist_for_new_board.md

**Comment by yokolet** [comment]
@davidchambers that's an old info. I forgot to update checklist. The latest is https://github.com/ClojureBridge/board/blob/master/ClojureBridge%20Stuff%20%26%20Where%20it%20Lives.md

For now, email is free since we are NPO under bridge foundry. Downside would be, someone needs to ask add/delete/change email to Bridge Foundry. As far as I know, Diana takes care of this sort. I'll find her email.
