### ISSUE TITLE
renew LastPass account subscription

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/board#13]
@mookerji just forwarded me an email from LastPass. Our account will expire in 31 days. Presumably we should renew our subscription before then. Do we have a bank account for such things?

**Comment by davidchambers** [comment]
Also, we should update the email address associated with the account to <info@clojurebridge.org>.

**Comment by yokolet** [comment]
Yes, we should update the subscription. The last time, @mookerji
<https://github.com/mookerji>  and Chris worked on the payment. I think
Chris remembers how to pay?

As for email address, I'm not sure where to set. I see David's name and
email in the primary business contact section. Did you, David, get the
notification email of the payment? At least, I did since I'm an
administrator.

Best,
- Yoko

**Comment by davidchambers** [comment]
> I think Chris remembers how to pay?

Okay. I will assign this issue to Chris.

> As for email address, I'm not sure where to set.

How about <info@clojurebridge.org>? That way messages will be sent to every board member rather than just one of us.

> I see David's name and email in the primary business contact section. Did you, David, get the notification email of the payment?

Buro updated the email address yesterday after contacting me.

**Comment by crkoehnen** [comment]
I'll take care of the renewal.  I also received the email notification.

**Comment by crkoehnen** [comment]
LastPass Enterprise Licenses for Clojurebridge

Total Valid Licenses: 7
Number of Licenses In-Use: 6
Number of Licenses Available: 1
Number of Users In Your Company: 6
Expiration: Monday, August 14, 2017 (3 weeks) : ABOUT TO EXPIRE


Number of Licenses: 7
Sub-Total: 117.60 (USD, before sales tax)

**Comment by crkoehnen** [comment]
According to the dashboard, it looks like we aren't using it very heavily.  Peak usage was July 2016 when it was used twice.

Are we really using it?

Should we renew or cancel?

**Comment by davidchambers** [comment]
I don't have access to LastPass (I don't know my master password) but this hasn't been a problem for me. Which sites require the use of a shared password stored in LastPass?

> Should we renew or cancel?

Cancelling the subscription would have no effect on me. @vsmart? @yokolet?

**Comment by vsmart** [comment]
I think we should renew it if we have the money/funds to do so. I'm not aware of any other easy solution to share passwords securely across a group of people.

**Comment by crkoehnen** [comment]
@vsmart, it's an easy solution for sharing passwords but are we really doing that?  It looks like the peak usage was twice one month last year.

There is money in the general fund to cover it but there's also the opportunity cost.  That money could go stickers or something for an event.

**Comment by davidchambers** [comment]
> Which sites require the use of a shared password stored in LastPass?

Could you answer this, @crkoehnen? I don't have access.

**Comment by mookerji** [comment]
I believe there are exactly three logins, the clj-bridge Twitter account, info@clojurebridge.org (Gmail), and Trello.

**Comment by davidchambers** [comment]
We can get a 30% discount on our LastPass subscription.

> Please send us your organization's government-approved non-profit form for evaluation. If applicable, please ensure that the form is addressed to GetGo, Inc., not LogMeIn, Inc.

@crkoehnen, can you provide me with such a form? I will then continue the process.

**Comment by vsmart** [comment]
@davidchambers I just had the thought that we could also downgrade to use one normal LastpassAccount rather than a team account. Those are free on the basic plan. And there is only one master pw we'd need to distribute (and we can rotate pws when people leave).

**Comment by davidchambers** [comment]
I like this idea, Franka. A 100% discount beats a 30% discount. :)

What do you think, @crkoehnen? What do you think, @yokolet?

**Comment by crkoehnen** [comment]
It sounds like:
2 votes for downgrading to a free, normal, non-team account.
1 vote for letting lastpass go.

If there are no objections, tomorrow I'll downgrade it.

**Comment by yokolet** [comment]
Sorry for the last minute response. After using LastPass for a year (or two?), I found LastPass is not so nice sharing tool among us. In my view, Passpack is a better option. ClojureBridge doesn't need to pay it. But, people may need to pay themselves depending on how heavily using/sharing on Passpack. Even though payment is required, it will be $5 or so per a year.

I'm not sure about how "downgrading to a free, normal, non-team account" works. It may or may not be a good choice.

**Comment by crkoehnen** [comment]
@yokolet , just in the nick of time.  :)

What do you dislike about LastPass?

What do you like about Passpack?

**Comment by crkoehnen** [comment]
There doesn't seem to be a way of downgrading to a non-team account.

I was planning to set up a new account, add twitter, google, and trello, then retire the enterprise account.  Unfortunately, while there's an option to see the passwords, I get a permission denied error.  I don't actually know what those passwords are.  I think I can use LastPass to go into twitter, google, and trello and change their passwords, then set up a new LastPass account.  I'll admit, I'm a little twitchy about it since I don't want to lock the accounts.

If somebody knows those passwords, we could set up with a new LastPass account before breaking the current account.

**Comment by crkoehnen** [comment]
It expires in 23 hours.  I'm sorry it was on my desk so long, but at this point, I'm tempted to say let's just renew it and sort out what we want for next year.

**Comment by yokolet** [comment]
@crkoehnen :)
I don't like LastPass' not nice management tool. It's hard to understand. I mistakenly made Anna's personal account disabled. It's my bad, however, UI and documents are hard to figure out. Also, not all members have used frequently because of its confusing way of accessing passwords/setup, I guess.

Passpack is very clear, simple to use. It doesn't have an app or browser plugin. So, every time people need to login at the website and type two kinds of passwords. But, sharing a password is easy. Also, using a shared password is easy as well. In our case, we don't need a group. Just sharing each password individually would work.

**Comment by yokolet** [comment]
@crkoehnen 
We need trello and twitter only for now. "info@clojurebridge.org" is not an account anymore. All emails are forwarded to all board members' name@clojurebridge.org address. Each member has his/her own password to access the email.

**Comment by crkoehnen** [comment]
@yokolet , I do find the LastPass UI confusing.

That's good that google is out of the way.

We were talking about moving away from trello if github works well.

@yokolet, do you know the trello and twitter passwords?  If so, want to try sharing them via Passpack?  I created an account.  (crkoehnen)

**Comment by crkoehnen** [comment]
@yokolet , it looks like if we went with Passpack as individuals, one individual would "own" the password and share it with the others?  Am i reading that right?

Or would we need the "group plan", $48/year, which would allow 15 shared users and 25 groups?

**Comment by yokolet** [comment]
@crkoehnen that's correct. Someone will own it if we choose a cheapest way.
The group plan may be an ideal one. The point is, for us, $48/year costs much or not. LastPass plan is less?

**Comment by yokolet** [comment]
Oh, I see. $117 for LastPass. Apparently, passpack is a good choice.

I have saved twitter and trello passwords to my personal passpack account. Don't worry even though LastPass enterprise is expired. If we go with LastPass, let's discuss later about this topic.

**Comment by crkoehnen** [comment]
@yokolet, if you have the passwords, then I won't worry about it for tonight.  :)

**Comment by davidchambers** [comment]
In summary, the only shared passwords are for Trello and Twitter, and since Yoko has both of these passwords stored securely we will not renew our LastPass subscription.

I'll close this issue, as no further action is required.

**Comment by mookerji** [comment]
🎉💀  🔑 💀  🎉
